### ISSUE TITLE
When using on Mac, trying to access docker desktop which is running on the machine returns page not found

### ISSUE THREAD

**Issue by matthew-plusprogramming** [cqbqdd11519/DockerClient#1]
![Screen Shot 2019-07-07 at 9 08 09 PM](https://user-images.githubusercontent.com/28150424/60782413-5bddaa80-a0fb-11e9-8acf-6e2626bca13d.png)
![Screen Shot 2019-07-07 at 9 07 58 PM](https://user-images.githubusercontent.com/28150424/60782414-5bddaa80-a0fb-11e9-8763-06cfa2d239ce.png)

**Comment by cqbqdd11519** [comment]
I'm not sure about Docker in Mac, but can you check if the docker daemon socket is located in '/var/run/docker.sock'?
If the socket is located in '/private/var/run/docker.sock' or in any other place, please replace '/var/run/docker.sock' in docker.cpp file into the actual location of the socket

**Comment by matthew-plusprogramming** [comment]
The daemon socket is located in /var/run/docker.sock
![Screen Shot 2019-07-07 at 9 27 18 PM](https://user-images.githubusercontent.com/28150424/60783103-06ef6380-a0fe-11e9-8a3b-e067831446a7.png)

**Comment by matthew-plusprogramming** [comment]
I just noticed that the alias points to itself which is nonexistent and I found some docker article about this. Just thought it might help troubleshoot what's going on.
![Screen Shot 2019-07-07 at 9 33 08 PM](https://user-images.githubusercontent.com/28150424/60783378-38b4fa00-a0ff-11e9-8b76-2213e4e86d36.png)
