### ISSUE TITLE
puzzle of the parameter of function create_container

### ISSUE THREAD

**Issue by ktxu1224** [cqbqdd11519/DockerClient#2]
Hi, thx a lot for ur dockerclient project, which worked for me. But I m puzzled of the params of function create_container, I have the following two questions:
1. If I wanna config the network and mount container's dir to specific dir of Host when create a new container, how can I do? If there are any meterials to refer to? 
2. what I can set is only as the result of function inspect_container().json(), that is jsonxx::Object Config shows?
Looking forward to ur reply. Thx a lot!

**Comment by cqbqdd11519** [comment]
This project just forwards the request to a docker engine using http API.
So you can use any parameter you use in docker CLI.
About valid parameters, please refer to https://docs.docker.com/engine/api/v1.24/ 

For mounting a volume and attaching a network, it should work if you put 'Volume' parameter and 'NetworkingConfig' parameter in your request object.
