### ISSUE TITLE
Access remote docker daemon over ssh?

### ISSUE THREAD

**Issue by aniongithub** [cqbqdd11519/DockerClient#9]
How can I access a remote docker daemon via SSH?

**Comment by cqbqdd11519** [comment]
What do you mean `via SSH`?

**Comment by aniongithub** [comment]
See here: https://betterprogramming.pub/docker-tips-access-the-docker-daemon-via-ssh-97cd6b44a53

`docker -H ssh://vagrant@192.168.5.178 run -ti alpine echo “hello”`

If you have passwordless ssh set up between two machines with SSH keys, accessing the docker daemon over SSH is more secure. This is the method `docker-machine` also uses internally.

**Comment by cqbqdd11519** [comment]
From a simple experiment, i found that with the ssh:// protocol, it executes `docker system dial-stdio` via SSH to proxy STDIO and puts HTTP message for making a request.

It is not supported by this project now, and there's no plan to support it, cuz i think there is too much to handle.
This project is just a simple http client.
